# -*- coding: utf-8 -*-
"""farm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THokj0vRKgSSR42UtvwalET2qGRvvVx4
"""

from google.colab import drive
drive.mount('/content/gdrive')

!pip install requests
!pip install python-firebase
!pip install jwt

from firebase import firebase
firebase = firebase.FirebaseApplication('https://fourofus-4a59c.firebaseio.com', authentication=None)

cd gdrive/My Drive/COLAB SHIT!!/DMCE

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_excel('./crop_data.xlsx')
Y = df.iloc[:, 6]
df = df.drop('Crops', axis= 1)

df = df.drop(df.columns[7], axis=1)

X = df
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40, random_state = 0)

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 1, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

#from sklearn.svm import SVC
#clf = SVC(gamma='auto')
#clf.fit(X_train, y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

cm

accuracy_score(y_test,y_pred)















